In [23]:
import pandas as pd

articles = pd.read_parquet("../../data/gold/articles.parquet")

articles.head()

,article_id,product_code,prod_name,detail_desc,product_type_name,product_group_name,graphical_appearance_name,colour_group_name,perceived_colour_value_name,perceived_colour_master_name,department_name,index_name,index_group_name,section_name,garment_group_name
0,108775015,108775,Strap top,Jersey top with narrow shoulder straps.,Vest top,Garment Upper body,Solid,Black,Dark,Black,Jersey Basic,Ladieswear,Ladieswear,Womens Everyday Basics,Jersey Basic
1,108775044,108775,Strap top,Jersey top with narrow shoulder straps.,Vest top,Garment Upper body,Solid,White,Light,White,Jersey Basic,Ladieswear,Ladieswear,Womens Everyday Basics,Jersey Basic
2,108775051,108775,Strap top (1),Jersey top with narrow shoulder straps.,Vest top,Garment Upper body,Stripe,Off White,Dusty Light,White,Jersey Basic,Ladieswear,Ladieswear,Womens Everyday Basics,Jersey Basic
3,110065001,110065,OP T-shirt (Idro),"Microfibre T-shirt bra with underwired, moulde...",Bra,Underwear,Solid,Black,Dark,Black,Clean Lingerie,Lingeries/Tights,Ladieswear,Womens Lingerie,"Under-, Nightwear"
4,110065002,110065,OP T-shirt (Idro),"Microfibre T-shirt bra with underwired, moulde...",Bra,Underwear,Solid,White,Light,White,Clean Lingerie,Lingeries/Tights,Ladieswear,Womens Lingerie,"Under-, Nightwear"

In [24]:
articles.shape

(105542, 15)

In [25]:
articles.info()

<class 'pandas.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 15 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  str
 3   detail_desc                   105542 non-null  str
 4   product_type_name             105542 non-null  category
 5   product_group_name            105542 non-null  category
 6   graphical_appearance_name     105542 non-null  category
 7   colour_group_name             105542 non-null  category
 8   perceived_colour_value_name   105542 non-null  category
 9   perceived_colour_master_name  105542 non-null  category
 10  department_name               105542 non-null  category
 11  index_name                    105542 non-null  category
 12  index_group_name              105542 non-null  category
 13  section_name                  105542 non-null  category
 14  garment_group_name            105542 non-null  category
dtypes: category(11), int64(2), str(2)
memory usage: 20.4 MB

In [26]:
articles.isna().sum()

article_id                      0
product_code                    0
prod_name                       0
detail_desc                     0
product_type_name               0
product_group_name              0
graphical_appearance_name       0
colour_group_name               0
perceived_colour_value_name     0
perceived_colour_master_name    0
department_name                 0
index_name                      0
index_group_name                0
section_name                    0
garment_group_name              0
dtype: int64

In [27]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = [
    "product_type_name",
    "product_group_name",
    "graphical_appearance_name",
    "colour_group_name",
    "perceived_colour_value_name",
    "perceived_colour_master_name",
    "department_name",
    "index_name",
    "index_group_name",
    "section_name",
    "garment_group_name"
]

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=True
)

categorical_matrix = encoder.fit_transform(articles[categorical_cols])

categorical_matrix.shape

(105542, 600)

In [28]:
color_cols = [
    "colour_group_name",
    "perceived_colour_value_name",
    "perceived_colour_master_name"
]

articles[color_cols].nunique()

colour_group_name               50
perceived_colour_value_name      8
perceived_colour_master_name    20
dtype: int64

In [29]:
color_mapping_check = articles.groupby("colour_group_name", observed=True).agg(
    unique_value_count=("perceived_colour_value_name", "nunique"),
    unique_master_count=("perceived_colour_master_name", "nunique")
)

color_mapping_check.sort_values(
    ["unique_value_count", "unique_master_count"],
    ascending=False
).head(20)

                   unique_value_count  unique_master_count
colour_group_name
Orange                              6                    5
Dark Blue                           5                    6
Dark Pink                           5                    5
Light Orange                        5                    5
Green                               5                    4
Pink                                5                    4
Turquoise                           5                    4
Blue                                5                    3
Light Pink                          5                    3
Light Yellow                        5                    3
Yellow                              5                    3
Dark Purple                         4                    5
Dark Green                          4                    4
Dark Orange                         4                    4
Dark Turquoise                      4                    2
Purple                              4                    2
Red                                 4                    2
Dark Yellow                         3                    6
Light Grey                          3                    6
Dark Red                            3                    5